name: Build docker image

on:
  push:
    branches:
    - main

    tags:
    - '*'

env:
  BASE_IMAGE_STABILITY_TAG: 2.14.1
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: '5.9'
        tags: 5.9,5,latest
